### PR TITLE
Add/Edit/Remove problem's test cases

### PR DESCRIPTION
**Pull request by maurostorch**
Dear developers,

I have made some changes on Problem editing pages to allow administrators and instructor to review, add and remove test cases.
Feel free to make tests. I have tested with Python and it works fine. I think it would work since the changes are made directly into the test cases files.

Best Regards.

### CODE REVIEW

**Comment by wojcik13** [comment]
HI,
thanks for that function, but my server don't hve editing or removing function. What to do?
Kindly regards

**Comment by wojcik13** [comment]
Hello, is there option to add an option to set for each testcase another time limit and memory limit?
Kind Regards

**Comment by maurostorch** [comment]
@wojcik13, the values for time limit and memory limit are regarding to the problem solving it self. It is not set per-testcase at this moment.

**Comment by wojcik13** [comment]
Yeah, I know, but I don't know how to make function to set these parameters for each testcase

**Comment by truongan** [comment]
You can start by looking at the tester.sh file,

**Comment by atiabjobayer** [comment]
Can you please do another upload system for test cases? @maurostorch , Please? :')

**Comment by atiabjobayer** [comment]
When I need to upload a big data like up to 2-3 mb, then my PC gets hang. An Upload system can solve the problem

**Comment by maurostorch** [comment]
Staled PR.

**Pull request closed without merging**
